package vues;

import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import modeles.*;
import javax.swing.JFrame;
import modeles.*;
import controleurs.*;
import static controleurs.CCategorie.catMap;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author darch
 */
public class Frame extends javax.swing.JFrame {

    public Frame() {
        GraphicsEnvironment graphics = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice device = graphics.getDefaultScreenDevice();   
        this.setUndecorated(true);
        
        
        initComponents();
        
        this.setResizable(false);
        //device.setFullScreenWindow(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        pan_ajout = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_catAjoutProd = new javax.swing.JTextField();
        tf_nomAjoutProd = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_prixAjoutProd = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_descAjoutProd = new javax.swing.JTextArea();
        bt_ajoutProd = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_nomSupprProd = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pan_ajout1 = new javax.swing.JPanel();
        bt_modCat = new javax.swing.JButton();
        lbl_ajoutCat = new javax.swing.JLabel();
        tf_ajoutCat = new javax.swing.JTextField();
        lbl_supprCat = new javax.swing.JLabel();
        tf_catModEx = new javax.swing.JTextField();
        bt_ajoutCat = new javax.swing.JButton();
        lbl_supprCat1 = new javax.swing.JLabel();
        tf_supprCat = new javax.swing.JTextField();
        bt_supprCat = new javax.swing.JButton();
        tf_catModNv = new javax.swing.JTextField();
        lbl_supprCat2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pan_ajout2 = new javax.swing.JPanel();
        mb_menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pan_ajout.setBackground(new java.awt.Color(102, 153, 255));
        pan_ajout.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel7.setText("Ajout");

        jLabel8.setText("Nom");

        tf_catAjoutProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_catAjoutProdActionPerformed(evt);
            }
        });

        tf_nomAjoutProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nomAjoutProdActionPerformed(evt);
            }
        });

        jLabel9.setText("Catégorie");

        jLabel10.setText("Prix");

        tf_prixAjoutProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_prixAjoutProdActionPerformed(evt);
            }
        });

        jLabel11.setText("Description");

        ta_descAjoutProd.setColumns(20);
        ta_descAjoutProd.setRows(5);
        jScrollPane1.setViewportView(ta_descAjoutProd);

        bt_ajoutProd.setText("Valider");
        bt_ajoutProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ajoutProdActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel12.setText("Suppression");

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel13.setText("Modification");

        tf_nomSupprProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nomSupprProdActionPerformed(evt);
            }
        });

        jLabel17.setText("Nom");

        jButton1.setText("Valider");

        javax.swing.GroupLayout pan_ajoutLayout = new javax.swing.GroupLayout(pan_ajout);
        pan_ajout.setLayout(pan_ajoutLayout);
        pan_ajoutLayout.setHorizontalGroup(
            pan_ajoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_ajoutLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pan_ajoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pan_ajoutLayout.createSequentialGroup()
                        .addGroup(pan_ajoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(tf_prixAjoutProd, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(tf_nomAjoutProd, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_catAjoutProd, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_ajoutProd)))
                .addGap(102, 102, 102)
                .addGroup(pan_ajoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_ajoutLayout.createSequentialGroup()
                        .addComponent(tf_nomSupprProd, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jButton1))
                    .addComponent(jLabel17))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pan_ajoutLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel7)
                .addGap(292, 292, 292)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(117, 117, 117))
        );
        pan_ajoutLayout.setVerticalGroup(
            pan_ajoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_ajoutLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(pan_ajoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pan_ajoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan_ajoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nomAjoutProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nomSupprProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(5, 5, 5)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan_ajoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pan_ajoutLayout.createSequentialGroup()
                        .addComponent(tf_catAjoutProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addComponent(bt_ajoutProd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_prixAjoutProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jLabel1.setText("Produits");

        jLabel2.setText("Catégories");

        pan_ajout1.setBackground(new java.awt.Color(102, 153, 255));
        pan_ajout1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        bt_modCat.setText("Valider");
        bt_modCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modCatActionPerformed(evt);
            }
        });

        lbl_ajoutCat.setText("Nom");

        lbl_supprCat.setText("Ancien nom");

        bt_ajoutCat.setText("Valider");
        bt_ajoutCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ajoutCatActionPerformed(evt);
            }
        });

        lbl_supprCat1.setText("Nom");

        bt_supprCat.setText("Valider");
        bt_supprCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_supprCatActionPerformed(evt);
            }
        });

        lbl_supprCat2.setText("Nouveau nom");

        jLabel14.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel14.setText("Ajout");

        jLabel15.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel15.setText("Suppression");

        jLabel16.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel16.setText("Modification");

        javax.swing.GroupLayout pan_ajout1Layout = new javax.swing.GroupLayout(pan_ajout1);
        pan_ajout1.setLayout(pan_ajout1Layout);
        pan_ajout1Layout.setHorizontalGroup(
            pan_ajout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_ajout1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pan_ajout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_ajout1Layout.createSequentialGroup()
                        .addComponent(tf_ajoutCat, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(bt_ajoutCat)
                        .addGap(135, 135, 135))
                    .addGroup(pan_ajout1Layout.createSequentialGroup()
                        .addComponent(lbl_ajoutCat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(pan_ajout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_supprCat1)
                    .addGroup(pan_ajout1Layout.createSequentialGroup()
                        .addComponent(tf_supprCat, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(bt_supprCat)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(pan_ajout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_ajout1Layout.createSequentialGroup()
                        .addComponent(lbl_supprCat)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pan_ajout1Layout.createSequentialGroup()
                        .addComponent(lbl_supprCat2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(tf_catModNv, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(bt_modCat)
                        .addGap(26, 26, 26))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_ajout1Layout.createSequentialGroup()
                .addGroup(pan_ajout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pan_ajout1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_catModEx, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pan_ajout1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel14)
                        .addGap(282, 282, 282)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)))
                .addGap(130, 130, 130))
        );
        pan_ajout1Layout.setVerticalGroup(
            pan_ajout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_ajout1Layout.createSequentialGroup()
                .addGroup(pan_ajout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_ajout1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pan_ajout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pan_ajout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pan_ajout1Layout.createSequentialGroup()
                                .addGroup(pan_ajout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_ajoutCat)
                                    .addComponent(lbl_supprCat1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pan_ajout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf_ajoutCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt_ajoutCat)
                                    .addComponent(tf_supprCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt_supprCat)))
                            .addGroup(pan_ajout1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(tf_catModEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tf_catModNv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pan_ajout1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(pan_ajout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt_modCat)
                            .addGroup(pan_ajout1Layout.createSequentialGroup()
                                .addComponent(lbl_supprCat)
                                .addGap(27, 27, 27)
                                .addComponent(lbl_supprCat2)))))
                .addGap(26, 26, 26))
        );

        jLabel3.setText("Promotions");

        pan_ajout2.setBackground(new java.awt.Color(102, 153, 255));
        pan_ajout2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        javax.swing.GroupLayout pan_ajout2Layout = new javax.swing.GroupLayout(pan_ajout2);
        pan_ajout2.setLayout(pan_ajout2Layout);
        pan_ajout2Layout.setHorizontalGroup(
            pan_ajout2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pan_ajout2Layout.setVerticalGroup(
            pan_ajout2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan_ajout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pan_ajout1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pan_ajout2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pan_ajout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(pan_ajout1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(pan_ajout2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("File");
        mb_menu.add(jMenu1);

        jMenu2.setText("Edit");
        mb_menu.add(jMenu2);

        setJMenuBar(mb_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 179, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_modCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modCatActionPerformed
        CCategorie ccategorie = new CCategorie();
        Connexion co = new Connexion();
        
        if(!tf_catModEx.getText().isEmpty() && !tf_catModNv.getText().isEmpty()) {
            ccategorie.modifierCategorie(co, tf_catModEx.getText(), tf_catModNv.getText());
        } else {
            JOptionPane.showMessageDialog(this, "Le(s) champ(s) de texte est vide");
        }
        
            
    }//GEN-LAST:event_bt_modCatActionPerformed

    private void bt_ajoutCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ajoutCatActionPerformed
        //vérifier si texte existant
        if(!tf_ajoutCat.getText().isEmpty()) {
            String nom = tf_ajoutCat.getText();
            Connexion co = new Connexion();
            CCategorie ccategorie = new CCategorie();
            ccategorie.ajoutCategorie(co, nom);
            JOptionPane.showMessageDialog(this, "La catégorie a bien été créée");
        } else {
            JOptionPane.showMessageDialog(this, "Le champ de texte est vide");
        }
    }//GEN-LAST:event_bt_ajoutCatActionPerformed

    private void bt_supprCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_supprCatActionPerformed
        
        //vérifier si texte existant
        if(!tf_supprCat.getText().isEmpty()) {
            String nom = tf_supprCat.getText();
            Connexion co = new Connexion();
            CCategorie ccategorie = new CCategorie();
            ccategorie.supprimerCategorie(co, nom);
            JOptionPane.showMessageDialog(this, "La catégorie a bien été supprimée");
        } else {
            JOptionPane.showMessageDialog(this, "Le champ de texte est vide");
        }
    }//GEN-LAST:event_bt_supprCatActionPerformed

    private void tf_catAjoutProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_catAjoutProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_catAjoutProdActionPerformed

    private void tf_nomAjoutProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nomAjoutProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nomAjoutProdActionPerformed

    private void tf_prixAjoutProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_prixAjoutProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_prixAjoutProdActionPerformed

    private void bt_ajoutProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ajoutProdActionPerformed
        Connexion co = new Connexion();
        CCategorie ccategorie = new CCategorie();
        ccategorie.getCategorieFromDB(co);
        CProduit cproduit = new CProduit();
        ccategorie.getCategorie();
        Integer idCat = ccategorie.getIdFromCategorie(catMap, tf_catAjoutProd.getText());
            
        if(!tf_nomAjoutProd.getText().isEmpty() && !tf_catAjoutProd.getText().isEmpty() 
                && !tf_prixAjoutProd.getText().isEmpty() && !ta_descAjoutProd.getText().isEmpty()) {
            if(ccategorie.existeCategorie(co, tf_catAjoutProd.getText())) {
                cproduit.ajoutProduit(co, tf_nomAjoutProd.getText(), idCat, Integer.parseInt(tf_prixAjoutProd.getText()), (String)ta_descAjoutProd.getText());
                JOptionPane.showMessageDialog(this, "Le produit a bien été ajouté");
            } else {
                JOptionPane.showMessageDialog(this, "La catégorie est inexistante");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Le(s) champ(s) de texte est vide");
        }
        
    }//GEN-LAST:event_bt_ajoutProdActionPerformed

    private void tf_nomSupprProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nomSupprProdActionPerformed

        Connexion co = new Connexion();
        CProduit cproduit = new CProduit();
            
        if(!tf_nomSupprProd.getText().isEmpty()) {
            cproduit.supprimerProduit(co, tf_nomSupprProd.getText());
            
        } else {
            JOptionPane.showMessageDialog(this, "Le(s) champ(s) de texte est vide");
        }
        
    }//GEN-LAST:event_tf_nomSupprProdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_ajoutCat;
    private javax.swing.JButton bt_ajoutProd;
    private javax.swing.JButton bt_modCat;
    private javax.swing.JButton bt_supprCat;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_ajoutCat;
    private javax.swing.JLabel lbl_supprCat;
    private javax.swing.JLabel lbl_supprCat1;
    private javax.swing.JLabel lbl_supprCat2;
    private javax.swing.JMenuBar mb_menu;
    private javax.swing.JPanel pan_ajout;
    private javax.swing.JPanel pan_ajout1;
    private javax.swing.JPanel pan_ajout2;
    private javax.swing.JPanel panel;
    private javax.swing.JTextArea ta_descAjoutProd;
    private javax.swing.JTextField tf_ajoutCat;
    private javax.swing.JTextField tf_catAjoutProd;
    private javax.swing.JTextField tf_catModEx;
    private javax.swing.JTextField tf_catModNv;
    private javax.swing.JTextField tf_nomAjoutProd;
    private javax.swing.JTextField tf_nomSupprProd;
    private javax.swing.JTextField tf_prixAjoutProd;
    private javax.swing.JTextField tf_supprCat;
    // End of variables declaration//GEN-END:variables

}
